html:
    vnu: https://validator.w3.org/nu/
    include: '**/*.+(htm|html|shtml)'
    ignore:
        - '**/node_modules/**'

css :
    vnu : https://validator.w3.org/nu/
    include : ' **/*.css '
    ignore :
        - ' **/node_modules/** '
